### ISSUE TITLE
npm install generates errors

### ISSUE THREAD

**Issue by gitclem** [backstopmedia/riot-book-example#26]
I'mn guessing this is all due to "bit rot..."

npm -v => 6.9.0
node -v . => v12.4.0
Mac OSX 10.14.5 (18F203)

I did `git clone https://github.com/backstopmedia/riot-book-example`
I followed the instructions in`README.md` file:

`npm install`

I got lots of warnings and deprecations, and unfortunately a number of C++ errors

```
In file included from In file included from ../fsevents.cc../fsevents.cc::66:
:
In file included from In file included from ../../nan/nan.h../../nan/nan.h::203203:
:
In file included from In file included from ../../nan/nan_new.h../../nan/nan_new.h::189189:
:
../../nan/nan_implementation_12_inl.h../../nan/nan_implementation_12_inl.h::103103::4242::  errorerror: : nono  viableviable  conversionconversion  fromfrom  'v8::Isolate *''v8::Isolate *'  toto  'Local<v8::Context>''Local<v8::Context>'

  return scope.Escape(v8::Function::New( isolate  return scope.Escape(v8::Function::New( isolate

                                         ^~~~~~~                                         ^~~~~~~



In file included from ../fsevents.ccIn file included from :../fsevents.cc6::
6In file included from :
../../nan/nan.hIn file included from :../../nan/nan.h203::
203In file included from :
../../nan/nan_new.hIn file included from :../../nan/nan_new.h189::
189:
../../nan/nan_implementation_12_inl.h../../nan/nan_implementation_12_inl.h::337337::3737::  errorerror: : tootoo  fewfew  argumentsarguments  toto  functionfunction  call,call,  expectedexpected  2,2,  havehave  11

  return v8::StringObject::New(value).As<v8::StringObject>();  return v8::StringObject::New(value).As<v8::StringObject>();

         ~~~~~~~~~~~~~~~~~~~~~      ^         ~~~~~~~~~~~~~~~~~~~~~      ^




In file included from ../fsevents.cc:6:
In file included from In file included from ../fsevents.cc../../nan/nan.h::6203:
:
In file included from In file included from ../../nan/nan.h../../nan/nan_new.h::203189:
:
In file included from ../../nan/nan_new.h../../nan/nan_implementation_12_inl.h::189337:
:58../../nan/nan_implementation_12_inl.h:: 337:58error::  expectederror : '(' for function-style cast or type construction
expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
  return v8::StringObject::New(value).As<v8::StringObject>();                                         ~~~~~~~~~~~~~~~~^

                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^



In file included from ../fsevents.cc:6:
../../nan/nan.h:In file included from 916../fsevents.cc::446::
 ../../nan/nan.h:error916: :44:no  matching errormember:  function nofor  matchingcall  memberto  function'ToString' for
 call to 'ToString'
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~^~~~~~~~
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~^~~~~~~~

[AND LOTS MORE...]

33 warnings and 14 errors generated.
33 warnings and 14 errors generated.
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1*** [Release/obj.target/fse/fsevents.o] Error 1


[AND THEN...]
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/cwang/Documents/riot/riot-book-example/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)

[AND MORE ERRORS]
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/cwang/.node-gyp/12.4.0/include/node/v8.h:5380:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:58: error: expected '(' for function-style cast or type construction
  return v8::StringObject::New(value).As<v8::StringObject>();
                                         ~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:337:60: error: expected expression
  return v8::StringObject::New(value).As<v8::StringObject>();
                                                           ^
[AND MORE ERRORS...]

14 warnings and 8 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cwang/Documents/riot/riot-book-example/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/cwang/Documents/riot/riot-book-example/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/cwang/Documents/riot/riot-book-example/node_modules/node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN eslint-loader@1.6.1 requires a peer of eslint@>=1.6.0 <4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I haven't looked at the source to see how easy it might be to fix this...

**Comment by collingreen** [comment]
Thanks for filing this - I suspect you're right about bit rot and hopefully it can be fixed with some version upgrades. As a stop gap you might be able to just bump the node-sass version in package.json  to the latest and see if it builds.

**Comment by neetjn** [comment]
Hey @gitclem,

This is due to `boost-geospatial-index` @ https://github.com/kuzzleio/boost-geospatial-index, which will need to update to be compatible with Node.js 12. This project is using an older version of sass/node-sass that depends on a C++ bridge to build binaries for faster processing. I'd update the project, but I don't want to cause discrepancies between the book and the source.

For the time being, I've tested on both node versions 8 and 10. I'll add a warning in the README for future readers/followers. If you're on mac osx you should be able to leverage either n or nvm to streamline upgrading or downgrading node versions.

n: https://www.npmjs.com/package/n
nvm: https://github.com/nvm-sh/nvm

Let us know if you need anymore help!
